server {
    listen 80;
    listen [::]:80;
    server_name batty.roybot.se;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name batty.roybot.se;

    ssl_certificate /etc/letsencrypt/live/batty.roybot.se/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/batty.roybot.se/privkey.pem;

    client_max_body_size 100m;

    location / {
        proxy_pass http://127.0.0.1:3147;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_buffering off;
        proxy_read_timeout 3600s;
    }
}
